image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (& означает, что в фоновом режиме - не блокируем терминал для запуска тестов)
  curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  sudo chmod +x /usr/local/bin/docker-compose
  sudo docker-compose up -d
  sleep 10
  sudo java -jar ./artifacts/aqa-shop.jar --spring.profiles.active=mysql &

build_script:
  - curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
  - docker-compose up -d
  - sleep 10
  - java -jar ./artifacts/aqa-shop.jar --spring.profiles.active=mysql &
  - chmod +x gradlew
  - ./gradlew test -Ddb.url=jdbc:mysql://localhost:3306/app -Dselenide.headless=true # запускаем тест, флаг --info позволяет выводить больше информации