image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (& означает, что в фоновом режиме - не блокируем терминал для запуска тестов)
  java -jar ./artifacts/aqa-shop.jar --spring.profiles.active=mysql &


build_script:
  - chmod +x gradlew
  - ./gradlew test -Ddb.url=jdbc:mysql://localhost:3306/app --info  # запускаем тест, флаг --info позволяет выводить больше информации