version: '3.2'
services:
  db_mysql:
    image: mysql:8.0.18
    ports:
      - 3306:3306
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
  db_postgres:
    image: postgres:12.1
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
  node:
    build: ./gate-simulator
    image: "node"
    ports:
      - 9999:9999